### ISSUE TITLE
unsupported format character ';' (0x3b) at index 195

### ISSUE THREAD

**Issue by chrisfilo** [vsoch/pybraincompare#11]
https://opbeat.com/neurovault/neurovault/errors/11/bcb0f3d749c24a26b0bef2010e86f411

**Comment by vsoch** [comment]
I removed the ";" from the javascript, and I hope that fixes the error. I was unable to replicate it locally.

**Comment by chrisfilo** [comment]
This is how you can replicate the problem:
	In [2]: specific_error = "bla bla"
	
	In [3]: 'd3.selectAll("svg.svglegend").remove();\nd3.selectAll("svg.svgplot").remove();\nd3.selectAll("pybrain").append("div").attr("class","alert alert-danger").attr("role","alert").attr("style","width:90%; margin-top:30px").text("Scatterplot Comparison Correlations Not Possible: %s!")' %(specific_error)
	---------------------------------------------------------------------------
	ValueError                                Traceback (most recent call last)
	<ipython-input-3-1353275b9ce8> in <module>()
	----> 1 'd3.selectAll("svg.svglegend").remove();\nd3.selectAll("svg.svgplot").remove();\nd3.selectAll("pybrain").append("div").attr("class","alert alert-danger").attr("role","alert").attr("style","width:90%; margin-top:30px").text("Scatterplot Comparison Correlations Not Possible: %s!")' %(specific_error)
	
	ValueError: unsupported format character ';' (0x3b) at index 195
	
The problem is that you did not escape the "%" character in "90%". You can solve this by using "%%":

	In [4]: 'd3.selectAll("svg.svglegend").remove();\nd3.selectAll("svg.svgplot").remove();\nd3.selectAll("pybrain").append("div").attr("class","alert alert-danger").attr("role","alert").attr("style","width:90%%; margin-top:30px").text("Scatterplot Comparison Correlations Not Possible: %s!")' %(specific_error)
	Out[4]: 'd3.selectAll("svg.svglegend").remove();\nd3.selectAll("svg.svgplot").remove();\nd3.selectAll("pybrain").append("div").attr("class","alert alert-danger").attr("role","alert").attr("style","width:90%; margin-top:30px").text("Scatterplot Comparison Correlations Not Possible: bla bla!")'

**Comment by vsoch** [comment]
Cool! I didn't know I needed to escape those. Of course now that I think of it, duh. Will fix this asap.

**Comment by vsoch** [comment]
Thanks! :tomato:
